global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mamtzetza'
    static_configs:
      - targets: ['mamtzetza:9090']
        labels:
          app: 'mamtzetza'
          service: 'stream-worker'
