name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Tests Repo
      uses: actions/checkout@v4

    - name: Checkout Component Repo
      uses: actions/checkout@v4
      with:
        repository: eldarush/omega-firefly-component
        path: ../omega-firefly-component

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore and Build
      run: |
        dotnet restore OmegaFireflyQaaSTests.slnx --configfile NuGet.config
        dotnet build OmegaFireflyQaaSTests.slnx --no-restore -c Release

    - name: Run Docker Compose End-to-End Tests
      run: |
        docker compose up --build --abort-on-container-exit --exit-code-from tests
