name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Tests Repo
      uses: actions/checkout@v4
      with:
        path: mamtzetza-qaas-tests

    - name: Checkout Component Repo
      uses: actions/checkout@v4
      with:
        repository: eldarush/Mamtzetza
        path: Mamtzetza

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore and Build
      working-directory: mamtzetza-qaas-tests
      run: |
        dotnet restore MamtzetzaTests.slnx --configfile NuGet.config
        dotnet build MamtzetzaTests.slnx --no-restore -c Release

    - name: Run Docker Compose End-to-End Tests
      working-directory: mamtzetza-qaas-tests
      run: |
        docker compose up --build --abort-on-container-exit --exit-code-from tests
